# Purpose:
#   Analyze job for scanning for security vulnerabilities running within a gitlab schedule
#
# Dependency:
#   Deployer task "security:check:composer"
#
security:composer:check:scheduled:
  stage: security
  dependencies: [ ]
  cache:
    key: security-$CI_JOB_NAME-$CI_COMMIT_REF_NAME
    paths:
      - vendor/xima/xima-deployer-tools/deployer/security/
  variables:
    GIT_STRATEGY: fetch
  script:
    - !reference [.check-deployment-dependencies, script]
    - vendor/bin/dep security:check:composer local --notify $DEPLOYER_CONFIG_ADDITIONAL_OPTION
  rules:
    - if: $CI_JOB_NAME == $SCHEDULE_TASK_NAME
      when: always
    - when: never
  resource_group: $CI_COMMIT_REF_NAME
