# Purpose:
#   Analyze job for checking all project files according the editorconfig
#
# Dependency:
#   Composer package "armin/editorconfig-cli" and a composer script "lint:editorconfig"
#
analyze:editorconfig:
  image:
    name: ${DEFAULT_IMAGE_BUILD_COMPOSER}
  stage: analyze
  needs:
    - build:php
  script:
    - composer run lint:editorconfig
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_COMMIT_TAG || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "pipeline" || $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_TAG == null
      when: always
