# Purpose:
#   Analyze job for normalizing the composer.json file
#
# Dependency:
#   Composer package "ergebnis/composer-normalize" and a composer script "lint:composer:normalize"
#
analyze:composer:lint:
  image:
    name: ${DEFAULT_IMAGE_BUILD_COMPOSER}
  stage: analyze
  needs:
    - build:php
  script:
    - composer run lint:composer:normalize
  rules:
    - if : $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_TAG == null
      changes:
        - "composer.json"
