# Purpose:
#   Stop an existing feature branch instance on a staging system by calling a downstream pipeline on the main branch (Receiver)
#
deploy:feature:stop:downstream:
  stage: deploy.feature
  extends:
    - .ssh
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: always
    - when: never
  script:
    - !reference [.check-deployment-dependencies, script]
    - vendor/bin/dep feature:stop stage --feature=$UPSTREAM_BRANCH $DEPLOYER_CONFIG_ADDITIONAL_OPTION
