# Purpose:
#   Cleanup an existing feature branch instance on a staging system by calling a downstream pipeline on the main branch (Sender)
#
deploy:feature:cleanup:
  stage: deploy.feature
  extends:
    - .ssh
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /$FEATURE_BRANCH_NAME_REGEX/
    - if: $CI_COMMIT_REF_NAME =~ /^feature-.*$/
    - if: $CI_COMMIT_REF_NAME == "main"
  variables:
    GIT_STRATEGY: none
    FEATURE_STOP_DOWNSTREAM_BRANCH: main
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form "variables[UPSTREAM_BRANCH]=$CI_COMMIT_REF_NAME" --form ref=$FEATURE_STOP_DOWNSTREAM_BRANCH "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"
  resource_group: $CI_COMMIT_REF_NAME
  environment:
    name: $CI_COMMIT_REF_NAME
    url: $ENVIRONMENT_URL
    action: stop
  when: manual
