# Purpose:
#   Deploy a feature branch instance on a staging system
#
deploy:feature:rollback:
  stage: deploy.feature
  extends:
    - .ssh
  needs:
    - build:php
    - build:node
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /$FEATURE_BRANCH_NAME_REGEX/
    - if: $CI_COMMIT_REF_NAME =~ /^feature-.*$/
    - if: $CI_COMMIT_REF_NAME == "main"
  variables:
    DEPLOYER_CONFIG_FEATURE_BRANCH_HOST: stage
  script:
    - vendor/bin/dep deploy:unlock $DEPLOYER_CONFIG_FEATURE_BRANCH_HOST --feature=$CI_COMMIT_REF_NAME $DEPLOYER_CONFIG_ADDITIONAL_OPTION
    - vendor/bin/dep rollback $DEPLOYER_CONFIG_FEATURE_BRANCH_HOST  --feature=$CI_COMMIT_REF_NAME $DEPLOYER_CONFIG_ADDITIONAL_OPTION
  when: manual
  allow_failure: true
