# Purpose:
#   Deploy a feature branch instance on a staging system
#
deploy:feature:
  stage: deploy.feature
  extends:
    - .ssh
  needs:
    - build:php
    - build:node
  rules:
    - if: $CI_COMMIT_TAG || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "pipeline" || $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^(main|feature-.*|[A-Z]{2,}-\d+-.*)$/
      when: always
  resource_group: $CI_COMMIT_REF_NAME
  variables:
    DEPLOYER_CONFIG_FEATURE_BRANCH_HOST: stage
    FEATURE_STOP_DOWNSTREAM_BRANCH: main
  script:
    - vendor/bin/dep deploy:unlock $DEPLOYER_CONFIG_FEATURE_BRANCH_HOST --feature=$CI_COMMIT_REF_NAME $DEPLOYER_CONFIG_ADDITIONAL_OPTION
    - vendor/bin/dep deploy $DEPLOYER_CONFIG_FEATURE_BRANCH_HOST --feature=$CI_COMMIT_REF_NAME $DEPLOYER_CONFIG_ADDITIONAL_OPTION
  environment:
    name: $CI_COMMIT_REF_NAME
    url: $ENVIRONMENT_URL
    on_stop: deploy:feature:cleanup
    auto_stop_in: 3 months
  allow_failure: false
