# Purpose:
#   Deploy a feature branch instance on a staging system
#
deploy:feature:rollback:
  stage: deploy.feature
  extends:
    - .ssh
  needs:
    - build:php
    - build:node
  rules:
    - if: $CI_COMMIT_TAG || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "pipeline" || $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^(main|feature-.*|[A-Z]{2,}-\d+-.*)$/
      when: manual
    - when: never
  variables:
    DEPLOYER_CONFIG_FEATURE_BRANCH_HOST: stage
  script:
    - vendor/bin/dep deploy:unlock $DEPLOYER_CONFIG_FEATURE_BRANCH_HOST --feature=$CI_COMMIT_REF_NAME $DEPLOYER_CONFIG_ADDITIONAL_OPTION
    - vendor/bin/dep rollback $DEPLOYER_CONFIG_FEATURE_BRANCH_HOST  --feature=$CI_COMMIT_REF_NAME $DEPLOYER_CONFIG_ADDITIONAL_OPTION
  allow_failure: true
